/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AggiungiTask: typeof import('./src/components/AggiungiTask.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ListaTask: typeof import('./src/components/ListaTask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SezioneProfilo: typeof import('./src/components/SezioneProfilo.vue')['default']
    Task: typeof import('./src/components/Task.vue')['default']
  }
}
